name: Orchestr8 CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint code
      run: flake8 .

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=/home/runner/work/Orchestr8/Orchestr8" >> $GITHUB_ENV

    - name: Print directory structure
      run: |
        ls -R

    - name: Print PYTHONPATH
      run: echo "PYTHONPATH is set to $PYTHONPATH"

    - name: Print directory structure
      run: ls -R /home/runner/work/Orchestr8/Orchestr8

    - name: Run tests
      run: pytest /home/runner/work/Orchestr8/Orchestr8/tests
